const assert=require('assert');
const {spawn}=require('child_process');
const fs=require('fs');
const os=require('os');
const path=require('path');
const Database=require('better-sqlite3');
const root=path.join(__dirname,'..');
const port=String(7000+Math.floor(Math.random()*400));
const dataDir=fs.mkdtempSync(path.join(os.tmpdir(),'wrenchpro-operations-'));
const child=spawn(process.execPath,[path.join(root,'server','index.js')],{cwd:root,env:{...process.env,PORT:port,WRENCHPRO_DATA:dataDir,NODE_ENV:'test'},stdio:['ignore','pipe','pipe']});
let output='';child.stdout.on('data',chunk=>{output+=chunk;});child.stderr.on('data',chunk=>{output+=chunk;});
const base='http://127.0.0.1:'+port;
async function raw(method,route,body){const response=await fetch(base+route,{method,headers:body===undefined?{}:{'content-type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});return{status:response.status,body:await response.json()};}
async function ok(method,route,body){const result=await raw(method,route,body);assert.ok(result.status<400,method+' '+route+': '+result.status+' '+JSON.stringify(result.body));return result.body;}
async function ready(){const start=Date.now();while(Date.now()-start<15000){if(child.exitCode!==null)throw new Error('Server exited early:\n'+output);try{if((await fetch(base+'/api/health')).ok)return;}catch(_){}await new Promise(resolve=>setTimeout(resolve,100));}throw new Error('Server did not start:\n'+output);}
(async()=>{
 try{
  await ready();
  let operations=await ok('GET','/api/operations');
  assert.strictEqual(operations.workflow_columns.length,9);
  assert.ok(operations.templates.some(template=>template.items.some(item=>item.item_name==='Brake pad thickness'&&item.position_label==='LF')));
  assert.ok(operations.templates.some(template=>template.items.some(item=>item.item_name==='Tread depth'&&item.measurement_unit==='32nds')));
  assert.ok(operations.templates.every(template=>template.items.every(item=>Array.isArray(item.quick_notes))));
  const customer=await ok('POST','/api/customers',{first:'Workflow',last:'Tester',phone:'555-0100'});
  const vehicle=await ok('POST','/api/vehicles',{customer_id:customer.id,year:2022,make:'Ford',model:'Transit',vin:'1FTBW1YK0NKA00001',miles:1000});
  const employee=await ok('POST','/api/employees',{first:'Taylor',last:'Tech',role:'Mechanic',status:'active',hourly_rate:30});
  const part=await ok('POST','/api/inventory',{name:'QA Brake Pad',part_number:'QA-100',cost:40,retail_price:80,quantity:10,reorder_qty:2});
  const job=await ok('POST','/api/jobs',{customer_id:customer.id,vehicle_id:vehicle.id,employee_id:employee.id,date:'2026-08-16',service:'Brake service',status:'Pending',items:[{type:'labor',description:'Brake labor',qty:1,rate:100,amount:100,taxable:0}]});
  assert.ok(job.items[0].id);
  const resource=await ok('POST','/api/operations/resources',{name:'Mobile Unit 1',resource_type:'mobile',active:true,position:10});
  const inProgress=operations.workflow_columns.find(column=>column.name==='In Progress');
  const assigned=await ok('PUT','/api/operations/jobs/'+job.id+'/workflow',{workflow_column_id:inProgress.id,resource_id:resource.id,promised_at:'2026-08-16T15:00',priority:'High'});
  assert.strictEqual(assigned.resource_id,resource.id);
  await ok('POST','/api/operations/authorizations',{job_id:job.id,item_type:'job_item',item_id:job.items[0].id,status:'approved',authorization_method:'In person',customer_name:'Workflow Tester',signature:'Workflow Tester'});
  const edited=await ok('PUT','/api/jobs/'+job.id,{service:job.service,repair_order_number:job.repair_order_number,date:job.date,status:'Pending',invoice_status:'Unpaid',items:[{...job.items[0],rate:125,amount:125}]});
  assert.strictEqual(edited.items[0].id,job.items[0].id);
  operations=await ok('GET','/api/operations');
  assert.deepStrictEqual(operations.authorizations.filter(auth=>auth.item_type==='job_item'&&auth.item_id===job.items[0].id).map(auth=>auth.status).sort(),['approved','pending']);
  await ok('POST','/api/operations/authorizations',{job_id:job.id,item_type:'job_item',item_id:job.items[0].id,status:'declined',authorization_method:'In person',customer_name:'Workflow Tester',notes:'Return next month'});
  operations=await ok('GET','/api/operations');
  assert.ok(operations.deferred_services.some(item=>item.customer_id===customer.id&&item.description==='Brake labor'));
  const reservation=await ok('POST','/api/operations/reservations',{job_id:job.id,inventory_id:part.id,quantity:3});
  assert.strictEqual((await raw('POST','/api/operations/reservations',{job_id:job.id,inventory_id:part.id,quantity:8})).status,409);
  await ok('PUT','/api/operations/reservations/'+reservation.id+'/release',{});
  const vendor=await ok('POST','/api/operations/vendors',{name:'QA Parts House'});
  const po=await ok('POST','/api/operations/purchase-orders',{vendor_id:vendor.id,job_id:job.id,status:'Ordered',items:[{inventory_id:part.id,description:part.name,part_number:part.part_number,quantity_ordered:4,quantity_received:0,unit_cost:35,add_to_inventory:true}]});
  operations=await ok('GET','/api/operations');const savedPo=operations.purchase_orders.find(order=>order.id===po.id);
  await ok('PUT','/api/operations/purchase-orders/'+po.id,{vendor_id:vendor.id,job_id:job.id,status:'Received',items:[{...savedPo.items[0],quantity_received:2}]});
  assert.strictEqual((await ok('GET','/api/inventory')).find(item=>item.id===part.id).quantity,12);
  const task=await ok('POST','/api/operations/tasks',{job_id:job.id,job_item_id:job.items[0].id,employee_id:employee.id,description:'Complete brake labor',estimated_hours:1,status:'Not Started'});
  await ok('PUT','/api/operations/tasks/'+task.id,{...task,employee_id:employee.id,description:task.description,estimated_hours:1,status:'Complete'});
  assert.ok((await ok('POST','/api/time',{employee_id:employee.id,job_id:job.id,job_item_id:job.items[0].id,type:'repair',clock_in:'2026-08-16T10:00',clock_out:'2026-08-16T11:00'})).id);
  assert.ok((await ok('POST','/api/operations/service-events',{job_id:job.id,event_type:'check-in',mileage:1250,fuel_level:'1/2',warning_lights:'None',exterior_damage:'Scratch',keys_received:'1 key',checklist:{'Mileage verified':true},photos:[]})).id);
  assert.strictEqual((await ok('GET','/api/vehicles')).find(item=>item.id===vehicle.id).miles,1250);
  const template=operations.templates[0];
  const inspection=await ok('POST','/api/inspections',{customer_id:customer.id,vehicle_id:vehicle.id,job_id:job.id,employee_id:employee.id,template_id:template.id,date:'2026-08-16',status:'Draft',items:[{category:'Brakes',item_name:'Brake pad thickness',position_label:'LF',input_type:'measurement',measurement_unit:'mm',measurement_value:2,condition:'fail',notes:'Below specification',recommendation:'Replace front brake pads',recommendation_status:'recommended'}]});
  const savedInspection=(await ok('GET','/api/inspections')).find(item=>item.id===inspection.id);
  assert.strictEqual(savedInspection.items[0].measurement_value,2);assert.strictEqual(savedInspection.items[0].position_label,'LF');
  operations=await ok('GET','/api/operations');assert.ok(operations.deferred_services.some(item=>item.source_type==='inspection_item'&&item.description==='Replace front brake pads'));
  const estimate=await ok('POST','/api/estimates',{customer_id:customer.id,vehicle_id:vehicle.id,date:'2026-08-16',status:'Draft',items:[{type:'labor',description:'Authorized estimate labor',qty:1,rate:90,amount:90,taxable:0}]});
  await ok('POST','/api/operations/authorizations',{estimate_id:estimate.id,item_type:'estimate_item',item_id:estimate.items[0].id,status:'approved',authorization_method:'Email',customer_name:'Workflow Tester',signature:'Workflow Tester'});
  const converted=await ok('POST','/api/estimates/'+estimate.id+'/convert',{});
  operations=await ok('GET','/api/operations');
  assert.ok(operations.authorizations.some(auth=>auth.job_id===converted.job_id&&auth.item_type==='job_item'&&auth.status==='approved'&&auth.signature==='Workflow Tester'),'Estimate line authorization did not follow the stable line into the repair order');
  const appointment=await ok('POST','/api/appointments',{cust:'Workflow Tester',customer_id:customer.id,vehicle_id:vehicle.id,service:'Follow-up',date:'2026-08-20',time:'09:00',duration_minutes:60,resource_id:resource.id,recurrence_rule:'weekly',recurrence_count:3});
  assert.strictEqual(appointment.recurrence_ids.length,3);
  assert.strictEqual((await raw('POST','/api/appointments',{cust:'Conflict',date:'2026-08-20',time:'09:30',duration_minutes:60,resource_id:resource.id})).status,409);
  const payment=await ok('POST','/api/payments',{customer_id:customer.id,job_id:job.id,description:'Brake service payment',amount:75,method:'Card',date:'2026-08-16'});
  const refund=await ok('POST','/api/payments/'+payment.id+'/refund',{amount:25,method:'Card',date:'2026-08-16',note:'QA partial refund'});
  assert.strictEqual(refund.amount,-25);assert.strictEqual(refund.parent_payment_id,payment.id);assert.strictEqual(refund.payment_type,'refund');
  assert.strictEqual((await raw('POST','/api/payments/'+payment.id+'/refund',{amount:51,method:'Card',date:'2026-08-16'})).status,400);
  const ledger=await ok('GET','/api/payments');assert.strictEqual(ledger.filter(row=>row.parent_payment_id===payment.id).length,1);
  assert.strictEqual((await raw('DELETE','/api/payments/'+payment.id)).status,409);
  const html=fs.readFileSync(path.join(root,'public','index.html'),'utf8');
  for(const marker of ['id="page-workflow"','function startWorkflowDrag(','function dropWorkflowJob(','function openInspectionReport(','function openCustomerStatement(','function refundPayment(','id="auf-signature"','Quick notes'])assert.ok(html.includes(marker),'Renderer is missing connected-operations feature: '+marker);
  assert.ok(html.includes("await apply?.(result)"),'Mutation dispatcher must await state application before reporting success');
  assert.ok(html.includes("Saving inspection} succeeded")===false,'Inspection success copy must not be hard-coded incorrectly');
  const db=new Database(path.join(dataDir,'wrenchpro.db'),{readonly:true});assert.strictEqual(db.pragma('integrity_check',{simple:true}),'ok');assert.deepStrictEqual(db.pragma('foreign_key_check'),[]);db.close();
  console.log('Connected operations QA passed');
 }finally{child.kill();if(child.exitCode===null)await new Promise(resolve=>{child.once('exit',resolve);setTimeout(resolve,2000);});fs.rmSync(dataDir,{recursive:true,force:true});}
})().catch(error=>{console.error(error.stack||error);console.error(output);process.exitCode=1;});
